### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by kgfig** [noelsison/VideoList#2]
Note: This does not include naming conventions and some minor issues. :)

* Make `selection` and `selectionArgs` null in `ContentListActivity.onCreateLoader()`. There's no need to append a where clause here since you are passing the Uri for the `MODULE_CONTENT` type.
* Make `selection` and `selectionArgs` null in `VideoPlayerActivity.onCreateLoader()` for the same reason but with `MEDIA_ITEM` type.
* In `VideoListContentProvider` the following lines overwrite the `selection` argument passed to the method for the `MODULE_CONTENT` and `MEDIA_ITEM` cases.
```
@Nullable
@Override
public Cursor query(Uri uri, String[] projection, String selection, String[] selectionArgs, String sortOrder) {
...
if (selection == null) {
    selection = ContentItemEntry.COLUM_MODULE_ID + " = " + uri.getLastPathSegment();
}
...
if (selection == null) {
    selection = "_ID = " + uri.getLastPathSegment();
}
```
* I think it's better to throw SQLExceptions than to catch them in `VideoListContentProvider`. Have the calling class handle the error and inform the user that something went wrong.

@noelsison2  (edited lots of typos in this issue lol)

**Comment by noelsison2** [comment]
> * Make `selection` and `selectionArgs` null in `ContentListActivity.onCreateLoader()`. There's no need to append a where clause here since you are passing the Uri for the `MODULE_CONTENT` type.
> * Make `selection` and `selectionArgs` null in `VideoPlayerActivity.onCreateLoader()` for the same reason but with `MEDIA_ITEM` type.

I'll follow what you did on using `SQLiteQueryBuilder.appendWhere` on the `uri.getLastPathSegment()`

> * In `VideoListContentProvider` the following lines overwrite the `selection` argument passed to the method for the `MODULE_CONTENT` and `MEDIA_ITEM` cases.

`selection` will be null to begin with because of `if (selection == null) { }`. I'll replace it with the use of `SQLiteQueryBuilder.appendWhere` to ensure that the selection id is set.

> * I think it's better to throw SQLExceptions than to catch them in `VideoListContentProvider`. Have the calling class handle the error and inform the user that something went wrong.

We can do that since the content provider is currently used internally by the app. Relevant if external access is required:
 - https://developer.android.com/guide/topics/providers/content-provider-creating.html#Query
 - http://stackoverflow.com/a/12012173
